"""empty message

Revision ID: 54e907fe1dee
Revises: bed868b7db21
Create Date: 2016-06-04 12:03:27.239508

"""

# revision identifiers, used by Alembic.
revision = '54e907fe1dee'
down_revision = 'bed868b7db21'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.add_column('users', sa.Column('file_img', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'file_img')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    ### end Alembic commands ###
