"""empty message

Revision ID: bed868b7db21
Revises: 2f24c7d859d5
Create Date: 2016-05-19 11:42:21.479027

"""

# revision identifiers, used by Alembic.
revision = 'bed868b7db21'
down_revision = '2f24c7d859d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    ### end Alembic commands ###
